import { v4 as uuidv4 } from "uuid";

const jsonDatasDummy = {
  measureTypeList: ["NUMBER", "PERCENT"],
  measureType: "NUMBER",
  categories: [
    {
      name: "Base Line, questions only",
      hasQuestions: null,
      hasSubCategories: null,
      intScore: null,
      percentScore: null,
      questions: [
        {
          id: uuidv4(),
          questionTypeList: [
            "TEXT",
            "DROPDOWN",
            "RADIO",
            "MULTICHECK",
            "INTEGER",
            "NUMBER",
          ],
          isRequired: null,
          questionType: "TEXT",
          defaultAnswer: null,
          answer: {
            textAnswer: "Rohit Kumar",
            intAnswer: null,
            floatAnswer: null,
            selectedChoices: null,
            evalScore: null,
          },
          choices: null,
          questionText: "What is your name",
        },
        {
          id: uuidv4(),
          questionTypeList: [
            "TEXT",
            "DROPDOWN",
            "RADIO",
            "MULTICHECK",
            "INTEGER",
            "NUMBER",
          ],
          isRequired: null,
          questionType: "INTEGER",
          defaultAnswer: null,
          answer: {
            textAnswer: null,
            intAnswer: 32,
            floatAnswer: null,
            selectedChoices: null,
            evalScore: null,
          },
          choices: null,
          questionText: "What is your age",
        },
        {
          id: uuidv4(),
          questionTypeList: [
            "TEXT",
            "DROPDOWN",
            "RADIO",
            "MULTICHECK",
            "INTEGER",
            "NUMBER",
          ],
          isRequired: null,
          questionType: "MULTICHECK",
          defaultAnswer: null,
          answer: {
            textAnswer: null,
            intAnswer: null,
            floatAnswer: null,
            selectedChoices: [
              {
                choiceTypeList: ["TEXT", "RADIO", "CHECK", "INTEGER", "NUMBER"],
                name: "Mathematics",
                displayValue: "Mathematics",
                choiceType: "CHECK",
                score: 10.0,
              },
              {
                choiceTypeList: ["TEXT", "RADIO", "CHECK", "INTEGER", "NUMBER"],
                name: "Science",
                displayValue: "Science",
                choiceType: "CHECK",
                score: 10.0,
              },
              {
                choiceTypeList: ["TEXT", "RADIO", "CHECK", "INTEGER", "NUMBER"],
                name: "History",
                displayValue: "History",
                choiceType: "CHECK",
                score: 10.0,
              },
            ],
            evalScore: null,
          },
          choices: [
            {
              choiceTypeList: ["TEXT", "RADIO", "CHECK", "INTEGER", "NUMBER"],
              name: "Mathematics",
              displayValue: "Mathematics",
              choiceType: "CHECK",
              score: 10.0,
            },
            {
              choiceTypeList: ["TEXT", "RADIO", "CHECK", "INTEGER", "NUMBER"],
              name: "Science",
              displayValue: "Science",
              choiceType: "CHECK",
              score: 10.0,
            },
            {
              choiceTypeList: ["TEXT", "RADIO", "CHECK", "INTEGER", "NUMBER"],
              name: "History",
              displayValue: "History",
              choiceType: "CHECK",
              score: 10.0,
            },
          ],
          questionText: "Pick your interest Topics",
        },
      ],
      subCategories: null,
    },
    {
      name: "Base Line, No Questions",
      hasQuestions: null,
      hasSubCategories: null,
      intScore: null,
      percentScore: null,
      questions: null,
      subCategories: [
        {
          name: "Sub Category with only Questions",
          hasQuestions: null,
          hasSubCategories: null,
          intScore: null,
          percentScore: null,
          questions: [
            {
              id: uuidv4(),
              questionTypeList: [
                "TEXT",
                "DROPDOWN",
                "RADIO",
                "MULTICHECK",
                "INTEGER",
                "NUMBER",
              ],
              isRequired: null,
              questionType: "TEXT",
              defaultAnswer: null,
              answer: {
                textAnswer: "Rohit Kumar",
                intAnswer: null,
                floatAnswer: null,
                selectedChoices: null,
                evalScore: null,
              },
              choices: null,
              questionText: "What is your name",
            },
            {
              questionTypeList: [
                "TEXT",
                "DROPDOWN",
                "RADIO",
                "MULTICHECK",
                "INTEGER",
                "NUMBER",
              ],
              isRequired: null,
              questionType: "INTEGER",
              defaultAnswer: null,
              answer: {
                textAnswer: null,
                intAnswer: 32,
                floatAnswer: null,
                selectedChoices: null,
                evalScore: null,
              },
              choices: null,
              questionText: "What is your age",
            },
            {
              questionTypeList: [
                "TEXT",
                "DROPDOWN",
                "RADIO",
                "MULTICHECK",
                "INTEGER",
                "NUMBER",
              ],
              isRequired: null,
              questionType: "MULTICHECK",
              defaultAnswer: null,
              answer: {
                textAnswer: null,
                intAnswer: null,
                floatAnswer: null,
                selectedChoices: [
                  {
                    choiceTypeList: [
                      "TEXT",
                      "RADIO",
                      "CHECK",
                      "INTEGER",
                      "NUMBER",
                    ],
                    name: "Mathematics",
                    displayValue: "Mathematics",
                    choiceType: "CHECK",
                    score: 10.0,
                  },
                  {
                    choiceTypeList: [
                      "TEXT",
                      "RADIO",
                      "CHECK",
                      "INTEGER",
                      "NUMBER",
                    ],
                    name: "Science",
                    displayValue: "Science",
                    choiceType: "CHECK",
                    score: 10.0,
                  },
                  {
                    choiceTypeList: [
                      "TEXT",
                      "RADIO",
                      "CHECK",
                      "INTEGER",
                      "NUMBER",
                    ],
                    name: "History",
                    displayValue: "History",
                    choiceType: "CHECK",
                    score: 10.0,
                  },
                ],
                evalScore: null,
              },
              choices: [
                {
                  choiceTypeList: [
                    "TEXT",
                    "RADIO",
                    "CHECK",
                    "INTEGER",
                    "NUMBER",
                  ],
                  name: "Mathematics",
                  displayValue: "Mathematics",
                  choiceType: "CHECK",
                  score: 10.0,
                },
                {
                  choiceTypeList: [
                    "TEXT",
                    "RADIO",
                    "CHECK",
                    "INTEGER",
                    "NUMBER",
                  ],
                  name: "Science",
                  displayValue: "Science",
                  choiceType: "CHECK",
                  score: 10.0,
                },
                {
                  choiceTypeList: [
                    "TEXT",
                    "RADIO",
                    "CHECK",
                    "INTEGER",
                    "NUMBER",
                  ],
                  name: "History",
                  displayValue: "History",
                  choiceType: "CHECK",
                  score: 10.0,
                },
              ],
              questionText: "Pick your interest Topics",
            },
          ],
          subCategories: null,
        },
        {
          name: "Sub Category with Questions and Sub-Category",
          hasQuestions: null,
          hasSubCategories: null,
          intScore: null,
          percentScore: null,
          questions: [
            {
              questionTypeList: [
                "TEXT",
                "DROPDOWN",
                "RADIO",
                "MULTICHECK",
                "INTEGER",
                "NUMBER",
              ],
              isRequired: null,
              questionType: "TEXT",
              defaultAnswer: null,
              answer: {
                textAnswer: "Rohit Kumar",
                intAnswer: null,
                floatAnswer: null,
                selectedChoices: null,
                evalScore: null,
              },
              choices: null,
              questionText: "What is your name",
            },
            {
              questionTypeList: [
                "TEXT",
                "DROPDOWN",
                "RADIO",
                "MULTICHECK",
                "INTEGER",
                "NUMBER",
              ],
              isRequired: null,
              questionType: "INTEGER",
              defaultAnswer: null,
              answer: {
                textAnswer: null,
                intAnswer: 32,
                floatAnswer: null,
                selectedChoices: null,
                evalScore: null,
              },
              choices: null,
              questionText: "What is your age",
            },
            {
              questionTypeList: [
                "TEXT",
                "DROPDOWN",
                "RADIO",
                "MULTICHECK",
                "INTEGER",
                "NUMBER",
              ],
              isRequired: null,
              questionType: "MULTICHECK",
              defaultAnswer: null,
              answer: {
                textAnswer: null,
                intAnswer: null,
                floatAnswer: null,
                selectedChoices: [
                  {
                    choiceTypeList: [
                      "TEXT",
                      "RADIO",
                      "CHECK",
                      "INTEGER",
                      "NUMBER",
                    ],
                    name: "Mathematics",
                    displayValue: "Mathematics",
                    choiceType: "CHECK",
                    score: 10.0,
                  },
                  {
                    choiceTypeList: [
                      "TEXT",
                      "RADIO",
                      "CHECK",
                      "INTEGER",
                      "NUMBER",
                    ],
                    name: "Science",
                    displayValue: "Science",
                    choiceType: "CHECK",
                    score: 10.0,
                  },
                  {
                    choiceTypeList: [
                      "TEXT",
                      "RADIO",
                      "CHECK",
                      "INTEGER",
                      "NUMBER",
                    ],
                    name: "History",
                    displayValue: "History",
                    choiceType: "CHECK",
                    score: 10.0,
                  },
                ],
                evalScore: null,
              },
              choices: [
                {
                  choiceTypeList: [
                    "TEXT",
                    "RADIO",
                    "CHECK",
                    "INTEGER",
                    "NUMBER",
                  ],
                  name: "Mathematics",
                  displayValue: "Mathematics",
                  choiceType: "CHECK",
                  score: 10.0,
                },
                {
                  choiceTypeList: [
                    "TEXT",
                    "RADIO",
                    "CHECK",
                    "INTEGER",
                    "NUMBER",
                  ],
                  name: "Science",
                  displayValue: "Science",
                  choiceType: "CHECK",
                  score: 10.0,
                },
                {
                  choiceTypeList: [
                    "TEXT",
                    "RADIO",
                    "CHECK",
                    "INTEGER",
                    "NUMBER",
                  ],
                  name: "History",
                  displayValue: "History",
                  choiceType: "CHECK",
                  score: 10.0,
                },
              ],
              questionText: "Pick your interest Topics",
            },
          ],
          subCategories: [
            {
              name: "Sub Category with only Questions",
              hasQuestions: null,
              hasSubCategories: null,
              intScore: null,
              percentScore: null,
              questions: [
                {
                  questionTypeList: [
                    "TEXT",
                    "DROPDOWN",
                    "RADIO",
                    "MULTICHECK",
                    "INTEGER",
                    "NUMBER",
                  ],
                  isRequired: null,
                  questionType: "TEXT",
                  defaultAnswer: null,
                  answer: {
                    textAnswer: "Rohit Kumar",
                    intAnswer: null,
                    floatAnswer: null,
                    selectedChoices: null,
                    evalScore: null,
                  },
                  choices: null,
                  questionText: "What is your name",
                },
                {
                  questionTypeList: [
                    "TEXT",
                    "DROPDOWN",
                    "RADIO",
                    "MULTICHECK",
                    "INTEGER",
                    "NUMBER",
                  ],
                  isRequired: null,
                  questionType: "INTEGER",
                  defaultAnswer: null,
                  answer: {
                    textAnswer: null,
                    intAnswer: 32,
                    floatAnswer: null,
                    selectedChoices: null,
                    evalScore: null,
                  },
                  choices: null,
                  questionText: "What is your age",
                },
                {
                  questionTypeList: [
                    "TEXT",
                    "DROPDOWN",
                    "RADIO",
                    "MULTICHECK",
                    "INTEGER",
                    "NUMBER",
                  ],
                  isRequired: null,
                  questionType: "MULTICHECK",
                  defaultAnswer: null,
                  answer: {
                    textAnswer: null,
                    intAnswer: null,
                    floatAnswer: null,
                    selectedChoices: [
                      {
                        choiceTypeList: [
                          "TEXT",
                          "RADIO",
                          "CHECK",
                          "INTEGER",
                          "NUMBER",
                        ],
                        name: "Mathematics",
                        displayValue: "Mathematics",
                        choiceType: "CHECK",
                        score: 10.0,
                      },
                      {
                        choiceTypeList: [
                          "TEXT",
                          "RADIO",
                          "CHECK",
                          "INTEGER",
                          "NUMBER",
                        ],
                        name: "Science",
                        displayValue: "Science",
                        choiceType: "CHECK",
                        score: 10.0,
                      },
                      {
                        choiceTypeList: [
                          "TEXT",
                          "RADIO",
                          "CHECK",
                          "INTEGER",
                          "NUMBER",
                        ],
                        name: "History",
                        displayValue: "History",
                        choiceType: "CHECK",
                        score: 10.0,
                      },
                    ],
                    evalScore: null,
                  },
                  choices: [
                    {
                      choiceTypeList: [
                        "TEXT",
                        "RADIO",
                        "CHECK",
                        "INTEGER",
                        "NUMBER",
                      ],
                      name: "Mathematics",
                      displayValue: "Mathematics",
                      choiceType: "CHECK",
                      score: 10.0,
                    },
                    {
                      choiceTypeList: [
                        "TEXT",
                        "RADIO",
                        "CHECK",
                        "INTEGER",
                        "NUMBER",
                      ],
                      name: "Science",
                      displayValue: "Science",
                      choiceType: "CHECK",
                      score: 10.0,
                    },
                    {
                      choiceTypeList: [
                        "TEXT",
                        "RADIO",
                        "CHECK",
                        "INTEGER",
                        "NUMBER",
                      ],
                      name: "History",
                      displayValue: "History",
                      choiceType: "CHECK",
                      score: 10.0,
                    },
                  ],
                  questionText: "Pick your interest Topics",
                },
              ],
              subCategories: null,
            },
          ],
        },
      ],
    },
  ],
};
export const storeJsonDatas = {
  measureTypeList: ["NUMBER", "PERCENT"],
  measureType: "NUMBER",
  categories: [
    {
      name: "Base Line, Questions only",
      hasQuestions: true,
      hasSubCategories: false,
      intScore: null,
      percentScore: null,
      level: "Level 1",
      weightage: 30,
      questions: [
        {
          id: uuidv4(),
          questionTypeList: [
            "TEXT",
            "DROPDOWN",
            "RADIO",
            "MULTICHECK",
            "INTEGER",
            "NUMBER",
          ],
          isRequired: null,
          questionType: "RADIO",
          defaultAnswer: null,
          answer: {
            textAnswer: "",
            intAnswer: null,
            floatAnswer: null,
            selectedChoices: null,
            evalScore: null,
          },
          choices: [
            {
              id: uuidv4(),
              choiceTypeList: ["TEXT", "RADIO", "CHECK", "INTEGER", "NUMBER"],
              name: "Positive",
              displayValue: "Positive?",
              choiceType: "RADIO",
              score: 10.0,
              selected: false,
            },
            {
              id: uuidv4(),
              choiceTypeList: ["TEXT", "RADIO", "CHECK", "INTEGER", "NUMBER"],
              name: "Negative",
              displayValue: "Negative?",
              choiceType: "RADIO",
              score: -10.0,
              selected: false,
            },
          ],
          questionText: "Would you like to choose Positive or Negative",
          questionId: "QID1001",
        },
        {
          id: uuidv4(),
          questionTypeList: [
            "TEXT",
            "DROPDOWN",
            "RADIO",
            "MULTICHECK",
            "INTEGER",
            "NUMBER",
          ],
          isRequired: null,
          questionType: "INTEGER",
          defaultAnswer: null,
          answer: {
            textAnswer: null,
            intAnswer: 32,
            floatAnswer: null,
            selectedChoices: null,
            evalScore: null,
          },
          choices: null,
          questionText: "What is your age",
        },
        {
          id: uuidv4(),
          questionTypeList: [
            "TEXT",
            "DROPDOWN",
            "RADIO",
            "MULTICHECK",
            "INTEGER",
            "NUMBER",
          ],
          isRequired: null,
          questionType: "MULTICHECK",
          defaultAnswer: null,
          answer: {
            textAnswer: null,
            intAnswer: null,
            floatAnswer: null,
            selectedChoices: [
              // {
              //   id: uuidv4(),
              //   choiceTypeList: ["TEXT", "RADIO", "CHECK", "INTEGER", "NUMBER"],
              //   name: "Mathematics",
              //   displayValue: "Mathematics",
              //   choiceType: "CHECK",
              //   score: 10.0,
              // },
              // {
              //   id: uuidv4(),
              //   choiceTypeList: ["TEXT", "RADIO", "CHECK", "INTEGER", "NUMBER"],
              //   name: "Science",
              //   displayValue: "Science",
              //   choiceType: "CHECK",
              //   score: 10.0,
              // },
              // {
              //   id: uuidv4(),
              //   choiceTypeList: ["TEXT", "RADIO", "CHECK", "INTEGER", "NUMBER"],
              //   name: "History",
              //   displayValue: "History",
              //   choiceType: "CHECK",
              //   score: 10.0,
              // },
            ],
            evalScore: null,
          },
          choices: [
            {
              id: uuidv4(),
              choiceTypeList: ["TEXT", "RADIO", "CHECK", "INTEGER", "NUMBER"],
              name: "Mathematics",
              displayValue: "Mathematics",
              choiceType: "CHECK",
              score: 10.0,
            },
            {
              id: uuidv4(),
              choiceTypeList: ["TEXT", "RADIO", "CHECK", "INTEGER", "NUMBER"],
              name: "Science",
              displayValue: "Science",
              choiceType: "CHECK",
              score: 10.0,
            },
            {
              id: uuidv4(),
              choiceTypeList: ["TEXT", "RADIO", "CHECK", "INTEGER", "NUMBER"],
              name: "History",
              displayValue: "History",
              choiceType: "CHECK",
              score: 10.0,
            },
          ],
          questionText: "Pick your interest Topics",
        },
      ],
      subCategories: null,
    },
    {
      name: "Base Line, With Only SubCategories",
      hasQuestions: false,
      hasSubCategories: true,
      intScore: null,
      percentScore: null,
      questions: null,
      level: "Level 1",
      weightage: 30,
      subCategories: [
        {
          id: uuidv4(),
          name: "Sub Category with only Questions",
          hasQuestions: true,
          hasSubCategories: false,
          intScore: null,
          percentScore: null,
          level: "Level 2",
          weightage: 15,
          questions: [
            {
              id: uuidv4(),
              questionTypeList: [
                "TEXT",
                "DROPDOWN",
                "RADIO",
                "MULTICHECK",
                "INTEGER",
                "NUMBER",
              ],
              isRequired: null,
              questionType: "TEXT",
              defaultAnswer: null,
              answer: {
                textAnswer: "Rohit Kumar",
                intAnswer: null,
                floatAnswer: null,
                selectedChoices: null,
                evalScore: null,
              },
              choices: null,
              questionText: "What is your name",
            },
            {
              id: uuidv4(),
              questionTypeList: [
                "TEXT",
                "DROPDOWN",
                "RADIO",
                "MULTICHECK",
                "INTEGER",
                "NUMBER",
              ],
              isRequired: null,
              questionType: "INTEGER",
              defaultAnswer: null,
              answer: {
                textAnswer: null,
                intAnswer: 32,
                floatAnswer: null,
                selectedChoices: null,
                evalScore: null,
              },
              choices: null,
              questionText: "What is your age",
            },
            {
              id: uuidv4(),
              questionTypeList: [
                "TEXT",
                "DROPDOWN",
                "RADIO",
                "MULTICHECK",
                "INTEGER",
                "NUMBER",
              ],
              isRequired: null,
              questionType: "MULTICHECK",
              defaultAnswer: null,
              answer: {
                textAnswer: null,
                intAnswer: null,
                floatAnswer: null,
                selectedChoices: [
                  {
                    id: uuidv4(),
                    choiceTypeList: [
                      "TEXT",
                      "RADIO",
                      "CHECK",
                      "INTEGER",
                      "NUMBER",
                    ],
                    name: "Mathematics",
                    displayValue: "Mathematics",
                    choiceType: "CHECK",
                    score: 10.0,
                  },
                  {
                    id: uuidv4(),
                    choiceTypeList: [
                      "TEXT",
                      "RADIO",
                      "CHECK",
                      "INTEGER",
                      "NUMBER",
                    ],
                    name: "Science",
                    displayValue: "Science",
                    choiceType: "CHECK",
                    score: 10.0,
                  },
                  {
                    id: uuidv4(),
                    choiceTypeList: [
                      "TEXT",
                      "RADIO",
                      "CHECK",
                      "INTEGER",
                      "NUMBER",
                    ],
                    name: "History",
                    displayValue: "History",
                    choiceType: "CHECK",
                    score: 10.0,
                  },
                ],
                evalScore: null,
              },
              choices: [
                {
                  id: uuidv4(),
                  choiceTypeList: [
                    "TEXT",
                    "RADIO",
                    "CHECK",
                    "INTEGER",
                    "NUMBER",
                  ],
                  name: "Mathematics",
                  displayValue: "Mathematics",
                  choiceType: "CHECK",
                  score: 10.0,
                },
                {
                  id: uuidv4(),
                  choiceTypeList: [
                    "TEXT",
                    "RADIO",
                    "CHECK",
                    "INTEGER",
                    "NUMBER",
                  ],
                  name: "Science",
                  displayValue: "Science",
                  choiceType: "CHECK",
                  score: 10.0,
                },
                {
                  id: uuidv4(),
                  choiceTypeList: [
                    "TEXT",
                    "RADIO",
                    "CHECK",
                    "INTEGER",
                    "NUMBER",
                  ],
                  name: "History",
                  displayValue: "History",
                  choiceType: "CHECK",
                  score: 10.0,
                },
              ],
              questionText: "Pick your interest Topics",
            },
          ],
          subCategories: null,
        },
        {
          id: uuidv4(),
          name: "Sub Category with Questions and Sub-Category",
          hasQuestions: true,
          hasSubCategories: true,
          intScore: null,
          percentScore: null,
          level: "Level 2",
          weightage: 15,
          questions: [
            {
              id: uuidv4(),
              questionTypeList: [
                "TEXT",
                "DROPDOWN",
                "RADIO",
                "MULTICHECK",
                "INTEGER",
                "NUMBER",
              ],
              isRequired: null,
              questionType: "TEXT",
              defaultAnswer: null,
              answer: {
                textAnswer: "Rohit Kumar",
                intAnswer: null,
                floatAnswer: null,
                selectedChoices: null,
                evalScore: null,
              },
              choices: null,
              questionText: "What is your name",
            },
            {
              id: uuidv4(),
              questionTypeList: [
                "TEXT",
                "DROPDOWN",
                "RADIO",
                "MULTICHECK",
                "INTEGER",
                "NUMBER",
              ],
              isRequired: null,
              questionType: "INTEGER",
              defaultAnswer: null,
              answer: {
                textAnswer: null,
                intAnswer: 32,
                floatAnswer: null,
                selectedChoices: null,
                evalScore: null,
              },
              choices: null,
              questionText: "What is your age",
            },
            {
              id: uuidv4(),
              questionTypeList: [
                "TEXT",
                "DROPDOWN",
                "RADIO",
                "MULTICHECK",
                "INTEGER",
                "NUMBER",
              ],
              isRequired: null,
              questionType: "MULTICHECK",
              defaultAnswer: null,
              answer: {
                textAnswer: null,
                intAnswer: null,
                floatAnswer: null,
                selectedChoices: [
                  {
                    id: uuidv4(),
                    choiceTypeList: [
                      "TEXT",
                      "RADIO",
                      "CHECK",
                      "INTEGER",
                      "NUMBER",
                    ],
                    name: "Mathematics",
                    displayValue: "Mathematics",
                    choiceType: "CHECK",
                    score: 10.0,
                  },
                  {
                    id: uuidv4(),
                    choiceTypeList: [
                      "TEXT",
                      "RADIO",
                      "CHECK",
                      "INTEGER",
                      "NUMBER",
                    ],
                    name: "Science",
                    displayValue: "Science",
                    choiceType: "CHECK",
                    score: 10.0,
                  },
                  {
                    id: uuidv4(),
                    choiceTypeList: [
                      "TEXT",
                      "RADIO",
                      "CHECK",
                      "INTEGER",
                      "NUMBER",
                    ],
                    name: "History",
                    displayValue: "History",
                    choiceType: "CHECK",
                    score: 10.0,
                  },
                ],
                evalScore: null,
              },
              choices: [
                {
                  id: uuidv4(),
                  choiceTypeList: [
                    "TEXT",
                    "RADIO",
                    "CHECK",
                    "INTEGER",
                    "NUMBER",
                  ],
                  name: "Mathematics",
                  displayValue: "Mathematics",
                  choiceType: "CHECK",
                  score: 10.0,
                },
                {
                  id: uuidv4(),
                  choiceTypeList: [
                    "TEXT",
                    "RADIO",
                    "CHECK",
                    "INTEGER",
                    "NUMBER",
                  ],
                  name: "Science",
                  displayValue: "Science",
                  choiceType: "CHECK",
                  score: 10.0,
                },
                {
                  id: uuidv4(),
                  choiceTypeList: [
                    "TEXT",
                    "RADIO",
                    "CHECK",
                    "INTEGER",
                    "NUMBER",
                  ],
                  name: "History",
                  displayValue: "History",
                  choiceType: "CHECK",
                  score: 10.0,
                },
              ],
              questionText: "Pick your interest Topics",
            },
          ],
          subCategories: [
            {
              id: uuidv4(),
              name: "Super Sub Category with only Questions",
              hasQuestions: true,
              hasSubCategories: false,
              intScore: null,
              percentScore: null,
              level: "Level 3",
              weightage: 10,
              questions: [
                {
                  id: uuidv4(),
                  questionTypeList: [
                    "TEXT",
                    "DROPDOWN",
                    "RADIO",
                    "MULTICHECK",
                    "INTEGER",
                    "NUMBER",
                  ],
                  isRequired: null,
                  questionType: "TEXT",
                  defaultAnswer: null,
                  answer: {
                    textAnswer: "Rohit Kumar",
                    intAnswer: null,
                    floatAnswer: null,
                    selectedChoices: null,
                    evalScore: null,
                  },
                  choices: null,
                  questionText: "What is your name",
                },
                {
                  id: uuidv4(),
                  questionTypeList: [
                    "TEXT",
                    "DROPDOWN",
                    "RADIO",
                    "MULTICHECK",
                    "INTEGER",
                    "NUMBER",
                  ],
                  isRequired: null,
                  questionType: "INTEGER",
                  defaultAnswer: null,
                  answer: {
                    textAnswer: null,
                    intAnswer: 32,
                    floatAnswer: null,
                    selectedChoices: null,
                    evalScore: null,
                  },
                  choices: null,
                  questionText: "What is your age",
                },
                {
                  id: uuidv4(),
                  questionTypeList: [
                    "TEXT",
                    "DROPDOWN",
                    "RADIO",
                    "MULTICHECK",
                    "INTEGER",
                    "NUMBER",
                  ],
                  isRequired: null,
                  questionType: "MULTICHECK",
                  defaultAnswer: null,
                  answer: {
                    textAnswer: null,
                    intAnswer: null,
                    floatAnswer: null,
                    selectedChoices: [
                      {
                        id: uuidv4(),
                        choiceTypeList: [
                          "TEXT",
                          "RADIO",
                          "CHECK",
                          "INTEGER",
                          "NUMBER",
                        ],
                        name: "Mathematics",
                        displayValue: "Mathematics",
                        choiceType: "CHECK",
                        score: 10.0,
                      },
                      {
                        id: uuidv4(),
                        choiceTypeList: [
                          "TEXT",
                          "RADIO",
                          "CHECK",
                          "INTEGER",
                          "NUMBER",
                        ],
                        name: "Science",
                        displayValue: "Science",
                        choiceType: "CHECK",
                        score: 10.0,
                      },
                      {
                        id: uuidv4(),
                        choiceTypeList: [
                          "TEXT",
                          "RADIO",
                          "CHECK",
                          "INTEGER",
                          "NUMBER",
                        ],
                        name: "History",
                        displayValue: "History",
                        choiceType: "CHECK",
                        score: 10.0,
                      },
                    ],
                    evalScore: null,
                  },
                  choices: [
                    {
                      id: uuidv4(),
                      choiceTypeList: [
                        "TEXT",
                        "RADIO",
                        "CHECK",
                        "INTEGER",
                        "NUMBER",
                      ],
                      name: "Mathematics",
                      displayValue: "Mathematics",
                      choiceType: "CHECK",
                      score: 10.0,
                    },
                    {
                      id: uuidv4(),
                      choiceTypeList: [
                        "TEXT",
                        "RADIO",
                        "CHECK",
                        "INTEGER",
                        "NUMBER",
                      ],
                      name: "Science",
                      displayValue: "Science",
                      choiceType: "CHECK",
                      score: 10.0,
                    },
                    {
                      id: uuidv4(),
                      choiceTypeList: [
                        "TEXT",
                        "RADIO",
                        "CHECK",
                        "INTEGER",
                        "NUMBER",
                      ],
                      name: "History",
                      displayValue: "History",
                      choiceType: "CHECK",
                      score: 10.0,
                    },
                  ],
                  questionText: "Pick your interest Topics",
                },
              ],
              subCategories: null,
            },
          ],
        },
      ],
    },
    {
      name: "Base Line, Questions and SubCategories",
      hasQuestions: true,
      hasSubCategories: true,
      intScore: null,
      percentScore: null,
      level: "Level 1",
      weightage: 40,
      questions: [
        {
          id: uuidv4(),
          questionTypeList: [
            "TEXT",
            "DROPDOWN",
            "RADIO",
            "MULTICHECK",
            "INTEGER",
            "NUMBER",
          ],
          isRequired: null,
          questionType: "TEXT",
          defaultAnswer: null,
          answer: {
            textAnswer: "Rohit Kumar",
            intAnswer: null,
            floatAnswer: null,
            selectedChoices: null,
            evalScore: null,
          },
          choices: null,
          questionText: "What is your name",
        },
        {
          id: uuidv4(),
          questionTypeList: [
            "TEXT",
            "DROPDOWN",
            "RADIO",
            "MULTICHECK",
            "INTEGER",
            "NUMBER",
          ],
          isRequired: null,
          questionType: "INTEGER",
          defaultAnswer: null,
          answer: {
            textAnswer: null,
            intAnswer: 32,
            floatAnswer: null,
            selectedChoices: null,
            evalScore: null,
          },
          choices: null,
          questionText: "What is your age",
        },
        {
          id: uuidv4(),
          questionTypeList: [
            "TEXT",
            "DROPDOWN",
            "RADIO",
            "MULTICHECK",
            "INTEGER",
            "NUMBER",
          ],
          isRequired: null,
          questionType: "MULTICHECK",
          defaultAnswer: null,
          answer: {
            textAnswer: null,
            intAnswer: null,
            floatAnswer: null,
            selectedChoices: [
              {
                id: uuidv4(),
                choiceTypeList: ["TEXT", "RADIO", "CHECK", "INTEGER", "NUMBER"],
                name: "Mathematics",
                displayValue: "Mathematics",
                choiceType: "CHECK",
                score: 10.0,
              },
              {
                id: uuidv4(),
                choiceTypeList: ["TEXT", "RADIO", "CHECK", "INTEGER", "NUMBER"],
                name: "Science",
                displayValue: "Science",
                choiceType: "CHECK",
                score: 10.0,
              },
              {
                id: uuidv4(),
                choiceTypeList: ["TEXT", "RADIO", "CHECK", "INTEGER", "NUMBER"],
                name: "History",
                displayValue: "History",
                choiceType: "CHECK",
                score: 10.0,
              },
            ],
            evalScore: null,
          },
          choices: [
            {
              id: uuidv4(),
              choiceTypeList: ["TEXT", "RADIO", "CHECK", "INTEGER", "NUMBER"],
              name: "Mathematics",
              displayValue: "Mathematics",
              choiceType: "CHECK",
              score: 10.0,
            },
            {
              id: uuidv4(),
              choiceTypeList: ["TEXT", "RADIO", "CHECK", "INTEGER", "NUMBER"],
              name: "Science",
              displayValue: "Science",
              choiceType: "CHECK",
              score: 10.0,
            },
            {
              id: uuidv4(),
              choiceTypeList: ["TEXT", "RADIO", "CHECK", "INTEGER", "NUMBER"],
              name: "History",
              displayValue: "History",
              choiceType: "CHECK",
              score: 10.0,
            },
          ],
          questionText: "Pick your interest Topics",
        },
      ],
      subCategories: [
        {
          id: uuidv4(),
          name: "Sub Category with only Questions",
          hasQuestions: true,
          hasSubCategories: false,
          intScore: null,
          percentScore: null,
          level: "Level 2",
          weightage: 15,
          questions: [
            {
              id: uuidv4(),
              questionTypeList: [
                "TEXT",
                "DROPDOWN",
                "RADIO",
                "MULTICHECK",
                "INTEGER",
                "NUMBER",
              ],
              isRequired: null,
              questionType: "TEXT",
              defaultAnswer: null,
              answer: {
                textAnswer: "Rohit Kumar",
                intAnswer: null,
                floatAnswer: null,
                selectedChoices: null,
                evalScore: null,
              },
              choices: null,
              questionText: "What is your name",
            },
            {
              id: uuidv4(),
              questionTypeList: [
                "TEXT",
                "DROPDOWN",
                "RADIO",
                "MULTICHECK",
                "INTEGER",
                "NUMBER",
              ],
              isRequired: null,
              questionType: "INTEGER",
              defaultAnswer: null,
              answer: {
                textAnswer: null,
                intAnswer: 32,
                floatAnswer: null,
                selectedChoices: null,
                evalScore: null,
              },
              choices: null,
              questionText: "What is your age",
            },
            {
              id: uuidv4(),
              questionTypeList: [
                "TEXT",
                "DROPDOWN",
                "RADIO",
                "MULTICHECK",
                "INTEGER",
                "NUMBER",
              ],
              isRequired: null,
              questionType: "MULTICHECK",
              defaultAnswer: null,
              answer: {
                textAnswer: null,
                intAnswer: null,
                floatAnswer: null,
                selectedChoices: [
                  {
                    id: uuidv4(),
                    choiceTypeList: [
                      "TEXT",
                      "RADIO",
                      "CHECK",
                      "INTEGER",
                      "NUMBER",
                    ],
                    name: "Mathematics",
                    displayValue: "Mathematics",
                    choiceType: "CHECK",
                    score: 10.0,
                  },
                  {
                    id: uuidv4(),
                    choiceTypeList: [
                      "TEXT",
                      "RADIO",
                      "CHECK",
                      "INTEGER",
                      "NUMBER",
                    ],
                    name: "Science",
                    displayValue: "Science",
                    choiceType: "CHECK",
                    score: 10.0,
                  },
                  {
                    id: uuidv4(),
                    choiceTypeList: [
                      "TEXT",
                      "RADIO",
                      "CHECK",
                      "INTEGER",
                      "NUMBER",
                    ],
                    name: "History",
                    displayValue: "History",
                    choiceType: "CHECK",
                    score: 10.0,
                  },
                ],
                evalScore: null,
              },
              choices: [
                {
                  id: uuidv4(),
                  choiceTypeList: [
                    "TEXT",
                    "RADIO",
                    "CHECK",
                    "INTEGER",
                    "NUMBER",
                  ],
                  name: "Mathematics",
                  displayValue: "Mathematics",
                  choiceType: "CHECK",
                  score: 10.0,
                },
                {
                  id: uuidv4(),
                  choiceTypeList: [
                    "TEXT",
                    "RADIO",
                    "CHECK",
                    "INTEGER",
                    "NUMBER",
                  ],
                  name: "Science",
                  displayValue: "Science",
                  choiceType: "CHECK",
                  score: 10.0,
                },
                {
                  id: uuidv4(),
                  choiceTypeList: [
                    "TEXT",
                    "RADIO",
                    "CHECK",
                    "INTEGER",
                    "NUMBER",
                  ],
                  name: "History",
                  displayValue: "History",
                  choiceType: "CHECK",
                  score: 10.0,
                },
              ],
              questionText: "Pick your interest Topics",
            },
          ],
          subCategories: null,
        },
        {
          id: uuidv4(),
          name: "Sub Category with Questions and Sub-Category",
          hasQuestions: true,
          hasSubCategories: true,
          intScore: null,
          percentScore: null,
          level: "Level 2",
          weightage: 20,
          questions: [
            {
              id: uuidv4(),
              questionTypeList: [
                "TEXT",
                "DROPDOWN",
                "RADIO",
                "MULTICHECK",
                "INTEGER",
                "NUMBER",
              ],
              isRequired: null,
              questionType: "TEXT",
              defaultAnswer: null,
              answer: {
                textAnswer: "Rohit Kumar",
                intAnswer: null,
                floatAnswer: null,
                selectedChoices: null,
                evalScore: null,
              },
              choices: null,
              questionText: "What is your name",
            },
            {
              id: uuidv4(),
              questionTypeList: [
                "TEXT",
                "DROPDOWN",
                "RADIO",
                "MULTICHECK",
                "INTEGER",
                "NUMBER",
              ],
              isRequired: null,
              questionType: "INTEGER",
              defaultAnswer: null,
              answer: {
                textAnswer: null,
                intAnswer: 32,
                floatAnswer: null,
                selectedChoices: null,
                evalScore: null,
              },
              choices: null,
              questionText: "What is your age",
            },
            {
              id: uuidv4(),
              questionTypeList: [
                "TEXT",
                "DROPDOWN",
                "RADIO",
                "MULTICHECK",
                "INTEGER",
                "NUMBER",
              ],
              isRequired: null,
              questionType: "MULTICHECK",
              defaultAnswer: null,
              answer: {
                textAnswer: null,
                intAnswer: null,
                floatAnswer: null,
                selectedChoices: [
                  {
                    id: uuidv4(),
                    choiceTypeList: [
                      "TEXT",
                      "RADIO",
                      "CHECK",
                      "INTEGER",
                      "NUMBER",
                    ],
                    name: "Mathematics",
                    displayValue: "Mathematics",
                    choiceType: "CHECK",
                    score: 10.0,
                  },
                  {
                    id: uuidv4(),
                    choiceTypeList: [
                      "TEXT",
                      "RADIO",
                      "CHECK",
                      "INTEGER",
                      "NUMBER",
                    ],
                    name: "Science",
                    displayValue: "Science",
                    choiceType: "CHECK",
                    score: 10.0,
                  },
                  {
                    id: uuidv4(),
                    choiceTypeList: [
                      "TEXT",
                      "RADIO",
                      "CHECK",
                      "INTEGER",
                      "NUMBER",
                    ],
                    name: "History",
                    displayValue: "History",
                    choiceType: "CHECK",
                    score: 10.0,
                  },
                ],
                evalScore: null,
              },
              choices: [
                {
                  id: uuidv4(),
                  choiceTypeList: [
                    "TEXT",
                    "RADIO",
                    "CHECK",
                    "INTEGER",
                    "NUMBER",
                  ],
                  name: "Mathematics",
                  displayValue: "Mathematics",
                  choiceType: "CHECK",
                  score: 10.0,
                },
                {
                  id: uuidv4(),
                  choiceTypeList: [
                    "TEXT",
                    "RADIO",
                    "CHECK",
                    "INTEGER",
                    "NUMBER",
                  ],
                  name: "Science",
                  displayValue: "Science",
                  choiceType: "CHECK",
                  score: 10.0,
                },
                {
                  id: uuidv4(),
                  choiceTypeList: [
                    "TEXT",
                    "RADIO",
                    "CHECK",
                    "INTEGER",
                    "NUMBER",
                  ],
                  name: "History",
                  displayValue: "History",
                  choiceType: "CHECK",
                  score: 10.0,
                },
              ],
              questionText: "Pick your interest Topics",
            },
          ],
          subCategories: [
            {
              id: uuidv4(),
              name: "Super Sub Category with only Questions",
              hasQuestions: true,
              hasSubCategories: false,
              intScore: null,
              percentScore: null,
              level: "Level 3",
              weightage: 15,
              questions: [
                {
                  id: uuidv4(),
                  questionTypeList: [
                    "TEXT",
                    "DROPDOWN",
                    "RADIO",
                    "MULTICHECK",
                    "INTEGER",
                    "NUMBER",
                  ],
                  isRequired: null,
                  questionType: "TEXT",
                  defaultAnswer: null,
                  answer: {
                    textAnswer: "Rohit Kumar",
                    intAnswer: null,
                    floatAnswer: null,
                    selectedChoices: null,
                    evalScore: null,
                  },
                  choices: null,
                  questionText: "What is your name",
                },
                {
                  id: uuidv4(),
                  questionTypeList: [
                    "TEXT",
                    "DROPDOWN",
                    "RADIO",
                    "MULTICHECK",
                    "INTEGER",
                    "NUMBER",
                  ],
                  isRequired: null,
                  questionType: "INTEGER",
                  defaultAnswer: null,
                  answer: {
                    textAnswer: null,
                    intAnswer: 32,
                    floatAnswer: null,
                    selectedChoices: null,
                    evalScore: null,
                  },
                  choices: null,
                  questionText: "What is your age",
                },
                {
                  id: uuidv4(),
                  questionTypeList: [
                    "TEXT",
                    "DROPDOWN",
                    "RADIO",
                    "MULTICHECK",
                    "INTEGER",
                    "NUMBER",
                  ],
                  isRequired: null,
                  questionType: "MULTICHECK",
                  defaultAnswer: null,
                  answer: {
                    textAnswer: null,
                    intAnswer: null,
                    floatAnswer: null,
                    selectedChoices: [
                      {
                        id: uuidv4(),
                        choiceTypeList: [
                          "TEXT",
                          "RADIO",
                          "CHECK",
                          "INTEGER",
                          "NUMBER",
                        ],
                        name: "Mathematics",
                        displayValue: "Mathematics",
                        choiceType: "CHECK",
                        score: 10.0,
                      },
                      {
                        id: uuidv4(),
                        choiceTypeList: [
                          "TEXT",
                          "RADIO",
                          "CHECK",
                          "INTEGER",
                          "NUMBER",
                        ],
                        name: "Science",
                        displayValue: "Science",
                        choiceType: "CHECK",
                        score: 10.0,
                      },
                      {
                        id: uuidv4(),
                        choiceTypeList: [
                          "TEXT",
                          "RADIO",
                          "CHECK",
                          "INTEGER",
                          "NUMBER",
                        ],
                        name: "History",
                        displayValue: "History",
                        choiceType: "CHECK",
                        score: 10.0,
                      },
                    ],
                    evalScore: null,
                  },
                  choices: [
                    {
                      id: uuidv4(),
                      choiceTypeList: [
                        "TEXT",
                        "RADIO",
                        "CHECK",
                        "INTEGER",
                        "NUMBER",
                      ],
                      name: "Mathematics",
                      displayValue: "Mathematics",
                      choiceType: "CHECK",
                      score: 10.0,
                    },
                    {
                      id: uuidv4(),
                      choiceTypeList: [
                        "TEXT",
                        "RADIO",
                        "CHECK",
                        "INTEGER",
                        "NUMBER",
                      ],
                      name: "Science",
                      displayValue: "Science",
                      choiceType: "CHECK",
                      score: 10.0,
                    },
                    {
                      id: uuidv4(),
                      choiceTypeList: [
                        "TEXT",
                        "RADIO",
                        "CHECK",
                        "INTEGER",
                        "NUMBER",
                      ],
                      name: "History",
                      displayValue: "History",
                      choiceType: "CHECK",
                      score: 10.0,
                    },
                  ],
                  questionText: "Pick your interest Topics",
                },
              ],
              subCategories: null,
            },
          ],
        },
      ],
    },
  ],
};

export const sampleCategories = {
  name: "Base Line, Questions and SubCategories",
  id: uuidv4(),
  first: "category -4",
  hasQuestions: true,
  hasSubCategories: true,
  intScore: null,
  percentScore: null,
  level: "Level 1",
  weightage: 40,
  questions: [
    {
      id: uuidv4(),
      questionTypeList: [
        "TEXT",
        "DROPDOWN",
        "RADIO",
        "MULTICHECK",
        "INTEGER",
        "NUMBER",
      ],
      isRequired: null,
      questionType: "TEXT",
      defaultAnswer: null,
      answer: {
        textAnswer: "Rohit Kumar",
        intAnswer: null,
        floatAnswer: null,
        selectedChoices: null,
        evalScore: null,
      },
      choices: null,
      questionText: "What is your name",
    },
    {
      id: uuidv4(),
      questionTypeList: [
        "TEXT",
        "DROPDOWN",
        "RADIO",
        "MULTICHECK",
        "INTEGER",
        "NUMBER",
      ],
      isRequired: null,
      questionType: "INTEGER",
      defaultAnswer: null,
      answer: {
        textAnswer: null,
        intAnswer: 32,
        floatAnswer: null,
        selectedChoices: null,
        evalScore: null,
      },
      choices: null,
      questionText: "What is your age",
    },
    {
      id: uuidv4(),
      questionTypeList: [
        "TEXT",
        "DROPDOWN",
        "RADIO",
        "MULTICHECK",
        "INTEGER",
        "NUMBER",
      ],
      isRequired: null,
      questionType: "MULTICHECK",
      defaultAnswer: null,
      answer: {
        textAnswer: null,
        intAnswer: null,
        floatAnswer: null,
        selectedChoices: [
          {
            id: uuidv4(),
            choiceTypeList: ["TEXT", "RADIO", "CHECK", "INTEGER", "NUMBER"],
            name: "Mathematics",
            displayValue: "Mathematics",
            choiceType: "CHECK",
            score: 10.0,
          },
          {
            id: uuidv4(),
            choiceTypeList: ["TEXT", "RADIO", "CHECK", "INTEGER", "NUMBER"],
            name: "Science",
            displayValue: "Science",
            choiceType: "CHECK",
            score: 10.0,
          },
          {
            id: uuidv4(),
            choiceTypeList: ["TEXT", "RADIO", "CHECK", "INTEGER", "NUMBER"],
            name: "History",
            displayValue: "History",
            choiceType: "CHECK",
            score: 10.0,
          },
        ],
        evalScore: null,
      },
      choices: [
        {
          id: uuidv4(),
          choiceTypeList: ["TEXT", "RADIO", "CHECK", "INTEGER", "NUMBER"],
          name: "Mathematics",
          displayValue: "Mathematics",
          choiceType: "CHECK",
          score: 10.0,
        },
        {
          id: uuidv4(),
          choiceTypeList: ["TEXT", "RADIO", "CHECK", "INTEGER", "NUMBER"],
          name: "Science",
          displayValue: "Science",
          choiceType: "CHECK",
          score: 10.0,
        },
        {
          id: uuidv4(),
          choiceTypeList: ["TEXT", "RADIO", "CHECK", "INTEGER", "NUMBER"],
          name: "History",
          displayValue: "History",
          choiceType: "CHECK",
          score: 10.0,
        },
      ],
      questionText: "Pick your interest Topics",
    },
  ],
  subCategories: [
    {
      id: uuidv4(),
      name: "Sub Category with only Questions",
      hasQuestions: true,
      hasSubCategories: false,
      intScore: null,
      percentScore: null,
      level: "Level 2",
      weightage: 15,
      questions: [
        {
          id: uuidv4(),
          questionTypeList: [
            "TEXT",
            "DROPDOWN",
            "RADIO",
            "MULTICHECK",
            "INTEGER",
            "NUMBER",
          ],
          isRequired: null,
          questionType: "TEXT",
          defaultAnswer: null,
          answer: {
            textAnswer: "Rohit Kumar",
            intAnswer: null,
            floatAnswer: null,
            selectedChoices: null,
            evalScore: null,
          },
          choices: null,
          questionText: "What is your name",
        },
        {
          id: uuidv4(),
          questionTypeList: [
            "TEXT",
            "DROPDOWN",
            "RADIO",
            "MULTICHECK",
            "INTEGER",
            "NUMBER",
          ],
          isRequired: null,
          questionType: "INTEGER",
          defaultAnswer: null,
          answer: {
            textAnswer: null,
            intAnswer: 32,
            floatAnswer: null,
            selectedChoices: null,
            evalScore: null,
          },
          choices: null,
          questionText: "What is your age",
        },
        {
          id: uuidv4(),
          questionTypeList: [
            "TEXT",
            "DROPDOWN",
            "RADIO",
            "MULTICHECK",
            "INTEGER",
            "NUMBER",
          ],
          isRequired: null,
          questionType: "MULTICHECK",
          defaultAnswer: null,
          answer: {
            textAnswer: null,
            intAnswer: null,
            floatAnswer: null,
            selectedChoices: [
              {
                id: uuidv4(),
                choiceTypeList: ["TEXT", "RADIO", "CHECK", "INTEGER", "NUMBER"],
                name: "Mathematics",
                displayValue: "Mathematics",
                choiceType: "CHECK",
                score: 10.0,
              },
              {
                id: uuidv4(),
                choiceTypeList: ["TEXT", "RADIO", "CHECK", "INTEGER", "NUMBER"],
                name: "Science",
                displayValue: "Science",
                choiceType: "CHECK",
                score: 10.0,
              },
              {
                id: uuidv4(),
                choiceTypeList: ["TEXT", "RADIO", "CHECK", "INTEGER", "NUMBER"],
                name: "History",
                displayValue: "History",
                choiceType: "CHECK",
                score: 10.0,
              },
            ],
            evalScore: null,
          },
          choices: [
            {
              id: uuidv4(),
              choiceTypeList: ["TEXT", "RADIO", "CHECK", "INTEGER", "NUMBER"],
              name: "Mathematics",
              displayValue: "Mathematics",
              choiceType: "CHECK",
              score: 10.0,
            },
            {
              id: uuidv4(),
              choiceTypeList: ["TEXT", "RADIO", "CHECK", "INTEGER", "NUMBER"],
              name: "Science",
              displayValue: "Science",
              choiceType: "CHECK",
              score: 10.0,
            },
            {
              id: uuidv4(),
              choiceTypeList: ["TEXT", "RADIO", "CHECK", "INTEGER", "NUMBER"],
              name: "History",
              displayValue: "History",
              choiceType: "CHECK",
              score: 10.0,
            },
          ],
          questionText: "Pick your interest Topics",
        },
      ],
      subCategories: null,
    },
    {
      id: uuidv4(),
      name: "Sub Category with Questions and Sub-Category",
      hasQuestions: true,
      hasSubCategories: true,
      intScore: null,
      percentScore: null,
      level: "Level 2",
      weightage: 20,
      questions: [
        {
          id: uuidv4(),
          questionTypeList: [
            "TEXT",
            "DROPDOWN",
            "RADIO",
            "MULTICHECK",
            "INTEGER",
            "NUMBER",
          ],
          isRequired: null,
          questionType: "TEXT",
          defaultAnswer: null,
          answer: {
            textAnswer: "Rohit Kumar",
            intAnswer: null,
            floatAnswer: null,
            selectedChoices: null,
            evalScore: null,
          },
          choices: null,
          questionText: "What is your name",
        },
        {
          id: uuidv4(),
          questionTypeList: [
            "TEXT",
            "DROPDOWN",
            "RADIO",
            "MULTICHECK",
            "INTEGER",
            "NUMBER",
          ],
          isRequired: null,
          questionType: "INTEGER",
          defaultAnswer: null,
          answer: {
            textAnswer: null,
            intAnswer: 32,
            floatAnswer: null,
            selectedChoices: null,
            evalScore: null,
          },
          choices: null,
          questionText: "What is your age",
        },
        {
          id: uuidv4(),
          questionTypeList: [
            "TEXT",
            "DROPDOWN",
            "RADIO",
            "MULTICHECK",
            "INTEGER",
            "NUMBER",
          ],
          isRequired: null,
          questionType: "MULTICHECK",
          defaultAnswer: null,
          answer: {
            textAnswer: null,
            intAnswer: null,
            floatAnswer: null,
            selectedChoices: [
              {
                id: uuidv4(),
                choiceTypeList: ["TEXT", "RADIO", "CHECK", "INTEGER", "NUMBER"],
                name: "Mathematics",
                displayValue: "Mathematics",
                choiceType: "CHECK",
                score: 10.0,
              },
              {
                id: uuidv4(),
                choiceTypeList: ["TEXT", "RADIO", "CHECK", "INTEGER", "NUMBER"],
                name: "Science",
                displayValue: "Science",
                choiceType: "CHECK",
                score: 10.0,
              },
              {
                id: uuidv4(),
                choiceTypeList: ["TEXT", "RADIO", "CHECK", "INTEGER", "NUMBER"],
                name: "History",
                displayValue: "History",
                choiceType: "CHECK",
                score: 10.0,
              },
            ],
            evalScore: null,
          },
          choices: [
            {
              id: uuidv4(),
              choiceTypeList: ["TEXT", "RADIO", "CHECK", "INTEGER", "NUMBER"],
              name: "Mathematics",
              displayValue: "Mathematics",
              choiceType: "CHECK",
              score: 10.0,
            },
            {
              id: uuidv4(),
              choiceTypeList: ["TEXT", "RADIO", "CHECK", "INTEGER", "NUMBER"],
              name: "Science",
              displayValue: "Science",
              choiceType: "CHECK",
              score: 10.0,
            },
            {
              id: uuidv4(),
              choiceTypeList: ["TEXT", "RADIO", "CHECK", "INTEGER", "NUMBER"],
              name: "History",
              displayValue: "History",
              choiceType: "CHECK",
              score: 10.0,
            },
          ],
          questionText: "Pick your interest Topics",
        },
      ],
      subCategories: [
        {
          id: uuidv4(),
          name: "Super Sub Category with only Questions",
          hasQuestions: true,
          hasSubCategories: false,
          intScore: null,
          percentScore: null,
          level: "Level 3",
          weightage: 15,
          questions: [
            {
              id: uuidv4(),
              questionTypeList: [
                "TEXT",
                "DROPDOWN",
                "RADIO",
                "MULTICHECK",
                "INTEGER",
                "NUMBER",
              ],
              isRequired: null,
              questionType: "TEXT",
              defaultAnswer: null,
              answer: {
                textAnswer: "Rohit Kumar",
                intAnswer: null,
                floatAnswer: null,
                selectedChoices: null,
                evalScore: null,
              },
              choices: null,
              questionText: "What is your name",
            },
            {
              id: uuidv4(),
              questionTypeList: [
                "TEXT",
                "DROPDOWN",
                "RADIO",
                "MULTICHECK",
                "INTEGER",
                "NUMBER",
              ],
              isRequired: null,
              questionType: "INTEGER",
              defaultAnswer: null,
              answer: {
                textAnswer: null,
                intAnswer: 32,
                floatAnswer: null,
                selectedChoices: null,
                evalScore: null,
              },
              choices: null,
              questionText: "What is your age",
            },
            {
              id: uuidv4(),
              questionTypeList: [
                "TEXT",
                "DROPDOWN",
                "RADIO",
                "MULTICHECK",
                "INTEGER",
                "NUMBER",
              ],
              isRequired: null,
              questionType: "MULTICHECK",
              defaultAnswer: null,
              answer: {
                textAnswer: null,
                intAnswer: null,
                floatAnswer: null,
                selectedChoices: [
                  {
                    id: uuidv4(),
                    choiceTypeList: [
                      "TEXT",
                      "RADIO",
                      "CHECK",
                      "INTEGER",
                      "NUMBER",
                    ],
                    name: "Mathematics",
                    displayValue: "Mathematics",
                    choiceType: "CHECK",
                    score: 10.0,
                  },
                  {
                    id: uuidv4(),
                    choiceTypeList: [
                      "TEXT",
                      "RADIO",
                      "CHECK",
                      "INTEGER",
                      "NUMBER",
                    ],
                    name: "Science",
                    displayValue: "Science",
                    choiceType: "CHECK",
                    score: 10.0,
                  },
                  {
                    id: uuidv4(),
                    choiceTypeList: [
                      "TEXT",
                      "RADIO",
                      "CHECK",
                      "INTEGER",
                      "NUMBER",
                    ],
                    name: "History",
                    displayValue: "History",
                    choiceType: "CHECK",
                    score: 10.0,
                  },
                ],
                evalScore: null,
              },
              choices: [
                {
                  id: uuidv4(),
                  choiceTypeList: [
                    "TEXT",
                    "RADIO",
                    "CHECK",
                    "INTEGER",
                    "NUMBER",
                  ],
                  name: "Mathematics",
                  displayValue: "Mathematics",
                  choiceType: "CHECK",
                  score: 10.0,
                },
                {
                  id: uuidv4(),
                  choiceTypeList: [
                    "TEXT",
                    "RADIO",
                    "CHECK",
                    "INTEGER",
                    "NUMBER",
                  ],
                  name: "Science",
                  displayValue: "Science",
                  choiceType: "CHECK",
                  score: 10.0,
                },
                {
                  id: uuidv4(),
                  choiceTypeList: [
                    "TEXT",
                    "RADIO",
                    "CHECK",
                    "INTEGER",
                    "NUMBER",
                  ],
                  name: "History",
                  displayValue: "History",
                  choiceType: "CHECK",
                  score: 10.0,
                },
              ],
              questionText: "Pick your interest Topics",
            },
          ],
          subCategories: null,
        },
      ],
    },
  ],
};
